group: lint
steps:
  - label: ":lint-roller: lint: {{matrix}}"
    key: lint-small
    tags:
      - lint
      - always
    depends_on:
      - forge
      - rust-pr-fast-fail
    commands:
      - ./ci/lint/lint.sh {{matrix}}
    matrix:
      - pre_commit
      - pytest_format
