name: "manylinux-$HOSTTYPE"
froms:
  - 192.168.7.176:5010/dockerhub/rayproject/manylinux2014:$MANYLINUX_VERSION-jdk-$HOSTTYPE
build_args:
  - BUILDKITE_BAZEL_CACHE_URL
  - MANYLINUX_VERSION
  - HOSTTYPE
dockerfile: ci/docker/manylinux-retag.Dockerfile
