#!/bin/bash
# This script is executed by Buildkite on the host machine.
# In contrast, our build jobs are run in Docker containers.
# This means that even though our build jobs write to
# `/artifact-mount`, the directory on the host machine is
# actually `/tmp/artifacts`.
# We clean up the artifacts directory before any command and
# after uploading artifacts to make sure no stale artifacts
# remain on the node when a Buildkite runner is re-used.
set -ex

ARTIFACT_DIR="${RAYCI_ARTIFACT_DIR:-/tmp/artifacts}"

if [ -d "$ARTIFACT_DIR" ]; then
    echo "Cleaning up artifacts after upload."
    echo "Artifact directory contents before cleanup:"
    find "$ARTIFACT_DIR" -print || true

    if [ "$(ls -A "$ARTIFACT_DIR")" ]; then
      echo "Directory not empty, cleaning up..."
      if [[ "${OSTYPE}" = darwin* ]]; then
        rm -rf "$ARTIFACT_DIR"
        mkdir -p "$ARTIFACT_DIR"
      else
        # Need to run in docker to avoid permission issues
        docker run --rm -v "$ARTIFACT_DIR":/artifact-mount alpine:latest /bin/sh -c 'rm -rf /artifact-mount/*; rm -rf /artifact-mount/.[!.]*' || true
      fi
    else
      echo "Directory already empty, no need to clean up."
    fi

    echo "Artifact directory contents after cleanup:"
    find "$ARTIFACT_DIR" -print || true
fi
